name: Bug repport
description: Create a bug report to help us improve
title: "<title>"
labels: ["bug"]
projects: "Cuby-board/2"

body:
    - type: textarea
      id: summary
      attributes:
          label: Summary
          description: One sentence description of what the bug is
          render: markdown
      validations:
          required: true

    - type: textarea
      id: step-to-reproduced
      attributes:
          label: How to reproduced
          description: The steps to recreate this bug
          value: |
              1. Go to '...'
              2. Click on '....'
              3. Scroll down to '....'
              4. **See error**
          render: markdown
      validations:
          required: true

    - type: textarea
      id: exepted-behavior
      attributes:
          label: Expected behavior
          description: A clear and concise description of what you expected to happen
          render: markdown
      validations:
          required: true

    - type: textarea
      id: screenshot
      attributes:
          label: Screenshot
          description: If needed paste here some screenshot of the bug
      validations:
          required: false

    - type: textarea
      id: stacktrace
      attributes:
          label: Stacktrace
          description: If you have a stacktrace or log, paste it between the quoted lines below
          render: shell
      validations:
          required: false

    - type: textarea
      id: other-detail
      attributes:
          label: Other detail
          description: Add any other context about the problem here. If not, leave blank
          render: markdown
      validations:
          required: false
